### ISSUE TITLE
JAR library References with identical file names

### ISSUE THREAD

**Issue by KwasiVT** [xamarin-bindings-for-twilio/TwilioVoiceXamarinAndroid#4]
Hi, I install the nuget package but when I went to build I received this error:

Severity	Code	Description	Project	Path	File	Line	Suppression State
Error		JAR library references with identical file names but different contents were found: libwebrtc.jar. Please remove any conflicting libraries from EmbeddedJar, InputJar and AndroidJavaLibrary.

I didn't not have this issue with your Video Nuget Package

**Comment by jtorvald** [comment]
@4brunu If I remember correctly in the .aar file you have a libs directory and in the Twilio Video package we used to open that .aar, rename it to zip, unzip, change the file libwebrtc.jar in the libs folder to libwebrtc2.jar, zip and rename to .aar again and use that as the code so those two files don't collide. 

Do I remember that correctly  @krnvd ?

**Comment by 4brunu** [comment]
Hum, I didn't knew that.
I didn't do that when I created a new version.

**Comment by krnvd** [comment]
@4brunu that's true. Sorry didn't mention that. Usually I did it for Twilio.Video library and the instructions were there.

Download aar/jar version you needed from https://bintray.com/twilio/releases/video-android and copy it to src\Jars. Then you will need to change res/values/values.xml and add missing <attr format="boolean" name="overlaySurface"/> attribute if needed. And rename /src/Jars/ARR/libs/libwebrtc.jar to libwebrtc_2.jar if you are going to use Twilio.Voice SDK in you project.

$ unzip video-android-7.0.3.aar -d tempFolder    
# Change whatever you need    
$ jar cvf video-android-7.0.3.aar -C tempFolder/ .

**Comment by 4brunu** [comment]
Thanks for the explanation.
In that case, Twilio Video Android and Twilio Voice Android should be released again to fix this issue.
Right now I don't have time for it.
If anyone wants to do it feel free, otherwise, I will try to do it, maybe later this week or in the weekend.

**Comment by jtorvald** [comment]
Only a new release of Video is required in that case. I will try to rename it now.

**Comment by 4brunu** [comment]
Thanks 👍

**Comment by jtorvald** [comment]
I created a PR with the renamed libwebrtc.jar file in the .jar: https://github.com/xamarin-bindings-for-twilio/TwilioVideoXamarinAndroid/pull/6

I didn't touch any values.xml for the overlay since I assume that this is already done.

**Comment by 4brunu** [comment]
I have released a new version to nuget that should fix this issue.
@KwasiVT could you please test this after Twilio Video Android 7.0.3.1 is available in nuget in a couple or hours?
Thanks

**Comment by KwasiVT** [comment]
Hey guys, I have tested the Video Android update and now the error is gone and it builds successfully. Thank you very much for your help

**Comment by 4brunu** [comment]
Nice 👍
