### ISSUE TITLE
Unable to use both Twilio.Video and Twilio.Audio Binding Libraries in Single Xamarin.Android App

### ISSUE THREAD

**Issue by codeanees** [xamarin-bindings-for-twilio/TwilioVoiceXamarinAndroid#5]
**Steps to reproduce:**
1. Create a Xamarin.Android app
2. Have both Twilio.Video and Twilio.Audio Binding Libraries
3. Refer the both Binding project in the Android app

**Error:**
Getting the below error.  If we refer either one of the library, we dont get any error.

<img width="1437" alt="Screenshot 2022-03-23 at 7 58 14 PM" src="https://user-images.githubusercontent.com/16783086/159722701-ac1a764a-e27a-45ae-96dd-c271e3a4b747.png">

**Comment by jtorvald** [comment]
@codeanees  this should be fixed when you update to Xamarin Twilio Video 7.0.3.1 nuget

**Comment by codeanees** [comment]
Yes, I did noticed.  Issue got resolved now!!!
